[package]
name = "xe"
version = "0.1.2+7"
edition = "2021"
authors = ["Vaibhav Pratap Singh <v8v88v8v88@protonmail.com>"]
description = "XE Programming Language"
license = "GPL-3.0-or-later"

[dependencies]
self_update = { version = "0.44.0", features = ["archive-tar", "compression-flate2", "archive-zip", "compression-zip-deflate"] }

[[test]]
name = "integration"
path = "tests/unit/basic_test.rs"
